###
POST http://localhost:8080/open-api/users/register
Content-Type: application/json

{
  "email": "test7@test.com",
  "name": "test7",
    "password": "qwer1234",
  "birthDay": "2002-01-02"
}

###
POST http://localhost:8080/open-api/users/login
Content-Type: application/json

{
  "email": "test7@test.com",
    "password": "qwer1234"
}

###
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMyIsImV4cCI6MTcwNDk1NjE0NX0.B9c8zDYkRdDF4Hp_wmipckRtu-H4wB-LVENYixqoQts

###
POST http://localhost:8080/api/stores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMSIsImV4cCI6MTcwMzkwMDYyOH0._VyDkQRd0NFX7PA3_LJwsP85vGIHty6w5U49UTVEASQ

{
    "name": "명태마을",
    "description": "명태조림 전문점",
    "address": "서울시 강남구",
    "phone": "000-0000-0000",
    "category": "KOREAN"
}

###
GET http://localhost:8080/open-api/store
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMyIsImV4cCI6MTcwNDk1NjE0NX0.B9c8zDYkRdDF4Hp_wmipckRtu-H4wB-LVENYixqoQts

###
POST http://localhost:8080/api/menus
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMyIsImV4cCI6MTcwNDk1NjE0NX0.B9c8zDYkRdDF4Hp_wmipckRtu-H4wB-LVENYixqoQts
Content-Type: application/json

{
      "name": "황금 명태조림",
        "description": "고급 명태조림",
        "price": 15000,
        "storeId": 1
}

###
GET http://localhost:8080/open-api/menus/stores/1

###
POST http://localhost:8080/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMyIsImV4cCI6MTcwNDk1NjE0NX0.B9c8zDYkRdDF4Hp_wmipckRtu-H4wB-LVENYixqoQts
Content-Type: application/json

{
  "totalAmount": 25000,
  "orderItems": [
    {
      "menuId": 1,
      "quantity": 1
    },
    {
      "menuId": 3,
      "quantity": 1
    }
  ]
}

###
GET http://localhost:8080/api/orders/users/13
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMyIsImV4cCI6MTcwNDk1NjE0NX0.B9c8zDYkRdDF4Hp_wmipckRtu-H4wB-LVENYixqoQts

###
GET http://localhost:8080/api/orders/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMyIsImV4cCI6MTcwNDk1NjE0NX0.B9c8zDYkRdDF4Hp_wmipckRtu-H4wB-LVENYixqoQts
