spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret-key: "fnlf93jfilfjkl23u930232hi4o3hofjou902ur9203rj23oknr2342yh34792u90f2fkl2n39ory79fy80923jnklnr32kl"
  access-token-expiration-seconds: 86400 # 1 day
  refresh-token-expiration-seconds: 604800 # 7 days